site_name: bookacle - Book Oracle
repo_url: https://github.com/MalayAgr/bookacle/
edit_uri: "edit/main/"

theme:
  name: material
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference
  font:
    text: Roboto
    code: Source Code Pro

markdown_extensions:
- attr_list
- smarty
- md_in_html
- admonition
- def_list
- meta
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.magiclink
- pymdownx.superfences
- pymdownx.keys
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- toc:
    baselevel: 1
    permalink: "¤"


plugins:
- search
- social
- autorefs
- markdown-exec
- minify:
    minify_html: true
    minify_js: true
    minify_css: true
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.txt
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://api.python.langchain.com/en/latest/objects.inv
          - https://pymupdf.readthedocs.io/en/latest/objects.inv
          - https://huggingface.co/docs/transformers/main/en/objects.inv
          - https://rich.readthedocs.io/en/stable/objects.inv
          - https://sbert.net/objects.inv
          - https://joblib.readthedocs.io/en/stable/objects.inv
          - https://www.dynaconf.com/objects.inv
        options:
          docstring_options:
            ignore_init_summary: true
          docstring_section_style: list
          filters: ["!^_", "^__init__$", "^__call__$", "!^can_replace$"]
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          parameter_headings: true
          separate_signature: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_source: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          signature_crossrefs: true
          summary: true
          members_order: source
          allow_inspection: true
          preload_modules: ["langchain_text_splitters"]

watch:
  - mkdocs.yml
  - src/bookacle/

extra_css:
  - stylesheets/custom.css


nav:
- Introduction: index.md
- Download and Install: download-install.md
- API Reference: reference/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MalayAgr
      name: Malay Agarwal on GitHub
