[project]
name = "bookacle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=3.4.3",
    "langchain>=0.2.15",
    "pypdf>=4.3.1",
    "python-dotenv>=1.0.1",
]

[project.scripts]
hello = "bookacle:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
