name: Deploy

on:
  push:
    tags:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --extra docs

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force --clean --verbose




